apiVersion: v1
kind: Pod
metadata:
  generateName: agent-k8s-
  labels:
    name: jnlptls
    label: jnlptls
spec:
  dnsConfig:
    options:
    - name: ndots
      value: "1"
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - name: jnlptls
    image: jenkins/jnlp-slave:3.26-1
    tty: true
    volumeMounts:
    - mountPath: /etc/ssl/certs/ca-certificates.crt
      name: volume-ca-bundle
      subPath: ca-certificates.crt
    - mountPath: /etc/ssl/certs/java/cacerts
      name: volume-ca-bundle
      subPath: cacerts
    - mountPath: /etc/default/cacerts
      name: volume-ca-bundle
      subPath: cacerts
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
  - name: gradle-6-0-1
    image: amd64/gradle:6.2.2-jdk11
    tty: true
    volumeMounts:
    - mountPath: /etc/ssl/certs/ca-certificates.crt
      name: volume-ca-bundle
      subPath: ca-certificates.crt
    - mountPath: /etc/ssl/certs/java/cacerts
      name: volume-ca-bundle
      subPath: cacerts
    - mountPath: /etc/default/cacerts
      name: volume-ca-bundle
      subPath: cacerts
  volumes:
  - configMap:
      defaultMode: 420
      name: ca-bundle
    name: volume-ca-bundle

