name: terragrunt shared environment

on:
  push:
    branches:
    - master
    - feature/*
    paths:
    - 'terraform/live/shared/**'
  pull_request:

jobs:
  terraform:
    name: terragrunt shared environment
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: 'asdf:install'
      uses: asdf-vm/actions/install@v1.0.0

    - name: 'terraform:provider:kubectl'
      run: |
        mkdir -p ~/.terraform.d/plugins
        curl -Ls https://api.github.com/repos/gavinbunney/terraform-provider-kubectl/releases/tags/v1.4.2  | jq -r ".assets[] | select(.browser_download_url | contains(\"$(uname -s | tr A-Z a-z)\")) | select(.browser_download_url | contains(\"amd64\")) | .browser_download_url" | xargs -n 1 curl -Lo ~/.terraform.d/plugins/terraform-provider-kubectl
        chmod +x ~/.terraform.d/plugins/terraform-provider-kubectl
    - name: 'terraform:setup'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false


    - name: 'aws:credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: 'terragrunt:init:vpc'
      run: terragrunt init
      working-directory: terraform/live/shared/eu-west-2/vpc

    - name: 'terragrunt:fmt:vpc'
      run: terragrunt fmt -check
      working-directory: terraform/live/shared/eu-west-2/vpc

    - name: 'terragrunt:validate:vpc'
      run: terragrunt validate
      working-directory: terraform/live/shared/eu-west-2/vpc

    - name: 'terragrunt:plan:vpc'
      run: terragrunt plan
      working-directory: terraform/live/shared/eu-west-2/vpc

    - name: 'terragrunt:apply:vpc'
      run: terragrunt apply -auto-approve
      working-directory: terraform/live/shared/eu-west-2/vpc

    - name: 'terragrunt:init:eks'
      run: terragrunt init
      working-directory: terraform/live/shared/eu-west-2/eks

    - name: 'terragrunt:fmt:eks'
      run: terragrunt fmt -check
      working-directory: terraform/live/shared/eu-west-2/eks

    - name: 'terragrunt:validate:eks'
      run: terragrunt validate
      working-directory: terraform/live/shared/eu-west-2/eks

    - name: 'terragrunt:plan:eks'
      run: terragrunt plan
      working-directory: terraform/live/shared/eu-west-2/eks

    - name: 'terragrunt:apply:eks'
      run: terragrunt apply -auto-approve
      working-directory: terraform/live/shared/eu-west-2/eks

    - name: 'terragrunt:init:eks-addons'
      run: terragrunt init
      working-directory: terraform/live/shared/eu-west-2/eks-addons

    - name: 'terragrunt:fmt:eks-addons'
      run: terragrunt fmt -check
      working-directory: terraform/live/shared/eu-west-2/eks-addons

    - name: 'terragrunt:validate:eks-addons'
      run: terragrunt validate
      working-directory: terraform/live/shared/eu-west-2/eks-addons

    - name: 'terragrunt:plan:eks-addons'
      run: terragrunt plan
      working-directory: terraform/live/shared/eu-west-2/eks-addons

    - name: 'terragrunt:apply:eks-addons'
      run: terragrunt apply -auto-approve
      working-directory: terraform/live/shared/eu-west-2/eks-addons

    - name: 'kubectl:wait-for-pods'
      run: kubectl --kubeconfig=kubeconfig wait --for=condition=Ready pods --all --all-namespaces --timeout 300s
      working-directory: terraform/live/shared/eu-west-2/eks

    - name: 'terragrunt:destroy:eks-addons'
      run: terragrunt destroy -auto-approve
      working-directory: terraform/live/shared/eu-west-2/eks-addons
      continue-on-error: true

    - name: 'terragrunt:destroy:eks-addons:cleanup-stale-state'
      run: terragrunt state list 2>/dev/null | xargs terragrunt state rm
      working-directory: terraform/live/shared/eu-west-2/eks-addons
      continue-on-error: true

    - name: 'terragrunt:destroy:eks'
      run: terragrunt destroy -auto-approve
      working-directory: terraform/live/shared/eu-west-2/eks
      continue-on-error: true

    - name: 'terragrunt:destroy:vpc'
      run: terragrunt destroy -auto-approve
      working-directory: terraform/live/shared/eu-west-2/vpc
      continue-on-error: true
